FROM postgres:16

# Variables d'environnement nécessaires pour initialiser la DB
# Ces valeurs doivent correspondre à celles du .env
ARG POSTGRES_USER=user
ARG POSTGRES_PASSWORD=postgrespassword
ARG POSTGRES_DB=calendar_db

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

# Copier les scripts SQL d'initialisation
COPY calendar_schema.sql /docker-entrypoint-initdb.d/01_schema.sql
COPY calendar_seed.sql /docker-entrypoint-initdb.d/02_seed.sql
